version: '3.3'

services:
  db:
    container_name: {{ db_container }}
    image: {{ db_image }}:{{ db_tag }}
    volumes:
      - db_data:/var/lib/mysql
      - ./create-exporter-user.sql:/docker-entrypoint-initdb.d/create-exporter-user.sql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: {{ db_root_password }}
      MYSQL_DATABASE: {{ db_name }}
      MYSQL_USER: {{ db_user }}
      MYSQL_PASSWORD: {{ db_password }}

  wordpress:
    container_name: {{ wordpress_container }}
    depends_on:
      - db
    image: {{ wordpress_image }}:{{ wordpress_tag }}
    volumes:
      - "./status.conf:/etc/apache2/mods-enabled/status.conf"
      - "./htaccess.conf:/var/www/html/.htaccess"
    ports:
      - "{{ wordpress_port }}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: {{ db_container }}:{{ db_port }}
      WORDPRESS_DB_USER: {{ db_user }}
      WORDPRESS_DB_PASSWORD: {{ db_password }}

volumes:
  db_data:
